name: NotTempBlock
version: '${project.version}'
main: me.ihqqq.notTempBlock
api-version: '1.21'
author: ihqqq

softdepend:
  - WorldGuard

commands:
  nottempblock:
    description: Lệnh chính của notTempBlock
    usage: /nottempblock <about|reload|gui>
    aliases:
      - ntb

permissions:
  nottempblock.about:
    description: Xem thông tin plugin
    default: true
  nottempblock.reload:
    description: Tải lại cấu hình plugin
    default: op
  nottempblock.bypass:
    description: Bỏ qua tính năng tự động xóa block/entity
    default: op
  nottempblock.gui:
    description: Mở GUI quản lý whitelist block
    default: op